// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		// Replace this comment with your code
		int N = Integer.parseInt(args[0]);
		int lessThenHalf = 0;
		int moreThenHalf = 0;
		int i = 1;
		double ratio = 1;

		while (i <= N) {
			double num = Math.random();
			if (num <= 0.5) {
				lessThenHalf = lessThenHalf + 1;
				i++;
			} else {
				moreThenHalf = moreThenHalf + 1;
				i++;
			}
		}

		System.out.println("> 0.5: " + lessThenHalf + " times");
		System.out.println("<= 0.5: " + moreThenHalf + " times");
		if (lessThenHalf != 0 && moreThenHalf != 0) {
			if (lessThenHalf > moreThenHalf) {
				ratio = (double) moreThenHalf / lessThenHalf;
			} else {
				ratio = (double) lessThenHalf / moreThenHalf;
			}

			System.out.println("Ratio: " + ratio);

		}

	}
}
